update reserve and release test device job

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -415,7 +415,7 @@ before_script:
     fi
     echo "current MR ID ${CI_MERGE_REQUEST_IID}";
     SUB_DIR="${CI_MERGE_REQUEST_IID}_${CI_PIPELINE_ID}";
-    NFS_CASE_FOLDER="${NFS_DST_DIR}/${SUB_DIR}/${CONF}/${DOMAIN}";
+    NFS_CASE_FOLDER="${NFS_DST_DIR}/${SUB_DIR}/${CONF}/${TEST_ENV}";
     echo "NFS_CASE_FOLDER: $NFS_CASE_FOLDER";
     echo "update current NFS_CASE_FOLDER permission before write";
     sudo mkdir -p ${NFS_CASE_FOLDER} || exit 1;
@@ -570,45 +570,29 @@ before_script:
       for i in {1..6}; do
         if [ $i -eq 6 ];
         then
-          echo "ERROR: No Available DUT after 5 times retry, Please rerun curent job to check it again";
-          exit 1;
+          echo "ERROR: No Available DUT after 5 times retry, Please rerun curent job to check it again"
+          exit 1
         fi
-        starttime=$(date +'%Y-%m-%d %H:%M:%S');
-        echo "---loop $i start time: $starttime";
-        echo "---start to get available test device in loop $i---";
-        available=$(./bin/ailab show --dest available --domain ${DOMAIN} --hw_type ${HW_TYPE} --hw_model ${HW_MODEL} --hw_ver ${HW_VER} --format args)
-        echo ${available}
-        if [[ $available =~ "k230" ]];
+        starttime=$(date +'%Y-%m-%d %H:%M:%S')
+        echo "---loop $i start time: $starttime"
+        echo "---start to get available test device in loop $i---"
+        echo "---start to get and reserve test device in loop $i---"
+        reserved=$(./bin/ailab reserve --domain ${TEST_ENV} --time 2h --hw_type ${HW_TYPE} --hw_model ${HW_MODEL} --hw_ver ${HW_VER} --format args --site $CI_PROJECT_NAME --source $CI_MERGE_REQUEST_IID --job $CI_PIPELINE_ID)
+        echo ${reserved}
+        if [[ $reserved =~ "k230" ]];
         then
-          echo "---Get Available DUT pass in loop $i---";
-          echo "----------get available test devices done----------";
-          echo "----------Step 2. reserve test device----------";
-          reserved=$(./bin/ailab add ${available} --time 15m --site ${CI_PROJECT_NAME} --source ${CI_MERGE_REQUEST_IID} --job ${CI_PIPELINE_ID} --format args);
-          echo ${reserved};
-          if [[ ${reserved} =~ "gitlab" ]];
-          then
-            echo "Reserve DUT pass in loop $i, break loop and continue the next job";
-            # exit for loop with break once device avaiable and reserved pass
-            break;
-          else
-            echo "ERROR: Reserve DUT failed";
-            if [ $i -eq 6 ];
-            then
-              echo "ERROR: No Available DUT after 5 times retry, Please rerun curent job to check it again";
-              exit 1;
-            else
-              echo "---sleep 30 seconds and auto rerun in next loop...";
-              sleep 30
-            fi
-          fi
+          echo "---get and reserve DUT pass in loop $i---"
+          echo "---get available test devices and reserve done----------"
+          echo "Reserve DUT pass in loop $i, break loop and continue the next job"
+          # exit for loop with break once device avaiable and reserved pass
+          break
         else
-          echo "ERROR: Get available test device failed in loop $i, ignore Error and try again...";
-          echo "---sleep for 30seconds and start to rerun in next loop...";
-          sleep 30;
+          echo "WARNING: No available test device in loop $i, retry..."
+          echo "---sleep for 60 seconds and retry in next loop..."
+          sleep 60;
         fi
       done
-    - echo "----------Step 3. save reserved/available for after_script----------"
-    - echo "${available}" > available
+    - echo "----------Step 2. save reserved for after_script----------"
     - echo "${reserved}" > reserved
     - echo "${HW_MODEL}" > HW_MODEL
     - echo "----------reserve test device and preprare test resource done----------"
@@ -617,14 +601,15 @@ before_script:
     - echo "----------release test device----------"
     - echo "get variables from previous steps"
     - reserved=$(cat reserved)
-    - available=$(cat available)
+    - echo $reserved
     - HW_MODEL=$(cat HW_MODEL)
+    - echo $HW_MODEL
     - echo "Release DUT start"
     - test -d bin || mkdir ./bin
     - test -f ./bin/ailab && rm -rf ./bin/ailab
     - wget -qc https://ai.b-bug.org/k230/test_resources/ci/tools/ailab -O ./bin/ailab
     - chmod +x ./bin/ailab
-    - result=$(./bin/ailab update --dest=reserved ${reserved})
+    - result=$(./bin/ailab update --dest=reserved --disabled 1 $(echo $reserved) )
     - echo $result
     - |
       if [[ $result =~ "True" ]]; then
@@ -633,28 +618,28 @@ before_script:
         echo "ERROR: Release DUT failed";
         exit 1;
       fi
-    - power_off="./bin/ailab power --type=off ${available}";
-    - power_on="./bin/ailab power --type=on ${available}";
-    - power_reset="./bin/ailab power --type=cycle ${available}";
+    - power_off="./bin/ailab power --type=off $(echo $reserved)"
+    - power_on="./bin/ailab power --type=on $(echo $reserved)"
+    - power_reset="./bin/ailab power --type=cycle $(echo $reserved)"
     - echo $power_off
     - echo $power_on
     - echo $power_reset
     - |
-      echo "---start to run device power job after test done...";
+      echo "---start to run device power job after test done..."
       if [[ "$HW_MODEL" =~ "evb" ]]; then
-        echo "---$HW_MODEL board will be power off and power on at test start---";
-        $power_off;
-        sleep 1;
-        $power_on;
-        sleep 1;
-        echo "$HW_MODEL board power off and power on done. continue in next loop";
+        echo "---$HW_MODEL board will be power off and power on at test start---"
+        $power_off
+        sleep 1
+        $power_on
+        sleep 1
+        echo "$HW_MODEL board power off and power on done. continue in next loop"
       else
-        echo "---$HW_MODEL board will be power reset at test start ---";
-        $power_reset;
-        sleep 1;
-        echo "---$HW_MODEL board power reset done. continue to run test job";
+        echo "---$HW_MODEL board will be power reset at test start ---"
+        $power_reset
+        sleep 1
+        echo "---$HW_MODEL board power reset done. continue to run test job"
       fi
-      echo "---device power job done---";
+      echo "---device power job done---"
     - echo "----------release test device done----------"
   copy_test_resource:
     - cd $CI_PROJECT_DIR
@@ -676,13 +661,13 @@ before_script:
     - pwd
     - echo "finished copy test resource in nfs_server"
     - echo "----------generate test device yml file for test job----------"
-    - echo "run command ./bin/ailab convert --dest=script --format yaml --file_name=${DOMAIN}.yml --nfs_server_ip $NFS_SERVER --nfs_case_folder $NFS_CASE_FOLDER --only_rtt ${ONLY_RTT} --only_linux ${ONLY_LINUX} --conf ${CONF} --pr_id ${CI_MERGE_REQUEST_IID} --job_id ${CI_PIPELINE_ID} --sysimage_md5 ${sysimage_md5} ${available}"
-    - ./bin/ailab convert --dest=script --format yaml --file_name=${DOMAIN}.yml --nfs_server_ip $NFS_SERVER --nfs_case_folder $NFS_CASE_FOLDER --only_rtt ${ONLY_RTT} --only_linux ${ONLY_LINUX} --conf ${CONF} --pr_id ${CI_MERGE_REQUEST_IID} --job_id ${CI_PIPELINE_ID} --sysimage_md5 ${sysimage_md5} ${available}
-    - test -f ${DOMAIN}.yml || exit 1
-    - cat ${DOMAIN}.yml || exit 1
-    - echo "cp ${DOMAIN}.yml to nfs_case_folder"
-    - cp -rf --sparse=always ${DOMAIN}.yml $NFS_CASE_FOLDER/ || exit 1
-    - test -f $NFS_CASE_FOLDER/${DOMAIN}.yml || exit 1
+    - echo "run command ./bin/ailab convert --dest=script --format yaml --file_name=${TEST_ENV}.yml --nfs_server_ip $NFS_SERVER --nfs_case_folder $NFS_CASE_FOLDER --only_rtt ${ONLY_RTT} --only_linux ${ONLY_LINUX} --conf ${CONF} --pr_id ${CI_MERGE_REQUEST_IID} --job_id ${CI_PIPELINE_ID} --sysimage_md5 ${sysimage_md5} $(echo $reserved)"
+    - ./bin/ailab convert --dest=script --format yaml --file_name=${TEST_ENV}.yml --nfs_server_ip $NFS_SERVER --nfs_case_folder $NFS_CASE_FOLDER --only_rtt ${ONLY_RTT} --only_linux ${ONLY_LINUX} --conf ${CONF} --pr_id ${CI_MERGE_REQUEST_IID} --job_id ${CI_PIPELINE_ID} --sysimage_md5 ${sysimage_md5} $(echo $reserved)
+    - test -f ${TEST_ENV}.yml || exit 1
+    - cat ${TEST_ENV}.yml || exit 1
+    - echo "cp ${TEST_ENV}.yml to nfs_case_folder"
+    - cp -rf --sparse=always ${TEST_ENV}.yml $NFS_CASE_FOLDER/ || exit 1
+    - test -f $NFS_CASE_FOLDER/${TEST_ENV}.yml || exit 1
     - echo "show test resource in nfs_server"
     - echo $NFS_CASE_FOLDER
     - ls -alht $NFS_CASE_FOLDER
@@ -696,9 +681,9 @@ before_script:
     - echo "MR ID ${CI_MERGE_REQUEST_IID}"
     - echo "Pipeline ID ${CI_PIPELINE_ID}"
     - echo "----------power on/reset test device before load image start----------"
-    - power_off="./bin/ailab power --type=off ${available}";
-    - power_on="./bin/ailab power --type=on ${available}";
-    - power_reset="./bin/ailab power --type=cycle ${available}";
+    - power_off="./bin/ailab power --type=off $(echo $reserved)"
+    - power_on="./bin/ailab power --type=on $(echo $reserved)"
+    - power_reset="./bin/ailab power --type=cycle $(echo $reserved)"
     - echo $power_off
     - echo $power_on
     - echo $power_reset
@@ -722,7 +707,7 @@ before_script:
       echo "---start to load image in for loop";
       stime=$(date +'%Y-%m-%d %H:%M:%S');
       echo "---load image start time: $stime";
-      load_cmd="./bin/aiload --file_name=$NFS_CASE_FOLDER/${DOMAIN}.yml";
+      load_cmd="./bin/aiload --file_name=$NFS_CASE_FOLDER/${TEST_ENV}.yml";
       echo "${load_cmd}";
       for i in {1..6}; do
         if [ $i -eq 6 ]
@@ -788,7 +773,7 @@ before_script:
       echo "---start to run k230 smoke test in for loop";
       stime=$(date +'%Y-%m-%d %H:%M:%S');
       echo "---run k230 smoke test start time: $stime";
-      test_cmd="./k230_linux_sdk_smoke_test.sh $NFS_CASE_FOLDER/${DOMAIN}.yml";
+      test_cmd="./k230_linux_sdk_smoke_test.sh $NFS_CASE_FOLDER/${TEST_ENV}.yml";
       for i in {1..3}; do
         if [ $i -eq 2 ];
         then
@@ -838,7 +823,7 @@ before_script:
       echo "---start to run k230 daily test in for loop";
       stime=$(date +'%Y-%m-%d %H:%M:%S');
       echo "---run k230 daily test start time: $stime";
-      test_cmd="./k230_linux_sdk_daily_test.sh $NFS_CASE_FOLDER/${DOMAIN}.yml";
+      test_cmd="./k230_linux_sdk_daily_test.sh $NFS_CASE_FOLDER/${TEST_ENV}.yml";
       for i in {1..3}; do
         if [ $i -eq 2 ];
         then
@@ -1044,7 +1029,7 @@ load_image_smoke_test:
   image: ai.b-bug.org:5000/k230_testscripts:latest
   stage: smoke_test
   variables:
-    DOMAIN: ai
+    TEST_ENV: ai
   parallel:
     matrix:
       - CONF:
@@ -1079,7 +1064,7 @@ daily_test:
   image: ai.b-bug.org:5000/k230_testscripts:latest
   stage: test
   variables:
-    DOMAIN: ai
+    TEST_ENV: ai
   parallel:
     matrix:
       - CONF:
